name: test
channels:
  - conda-forge
  - defaults
dependencies:
  - click=8.1.7
  - cmake=3.21.3
  - compilers=1.5.2
  - jinja2=3.1.20
  - numpy=1.26.0
  - pip=23.3.1
  - pybind11=2.11.12
  - pybind11-global=2.11.1
  - scikit-build=0.17.6
  - setuptools=68.0.0
  - spglib=2.1.00
  - wheel=0.41.2
  - pip:
      - ase==3.22.1
      - colorama==0.4.6
      - commonmark==0.9.1
      - matplotlib==3.8.0
      - networkx==3.2.1
      - pretty-errors==1.2.25
      - recommonmark==0.7.1
      - rich==13.7.0
      - scipy==1.11.3
      - typer==0.9.0
