name: test
channels:
  - conda-forge
  - defaults
dependencies:
  - click=8.1
  - cmake=3.21
  - compilers=1.5
  - jinja2=3.1
  - numpy=1.26
  - pip=23.3
  - pybind11=2.11
  - pybind11-global=2.11
  - scikit-build=0.17
  - setuptools=68.0
  - spglib=2.1
  - wheel=0.41
  - pip:
      - ase==3.22
      - colorama==0.4
      - commonmark==0.9
      - matplotlib==3.8
      - networkx==3.2
      - pretty-errors==1.2.25
      - recommonmark==0.7
      - rich==13.7
      - scipy==1.11
      - typer==0.9
