[build-system]
requires = [
  "setuptools>=42",
  "wheel",
  "scikit-build",
  "cmake",
  "pybind11",
  "numpy",
  "spglib",
  "ninja; platform_system!='Windows'"
]
build-backend = "setuptools.build_meta"